server:
  port: 8067

spring:
  datasource:
    url: jdbc:mysql://192.168.95.100:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
