server:
  port: 10008


spring:
  redis:
    host: 192.168.95.100
    port: 6379
    password: 123456
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 80
        max-wait: 30000
        timeout: 3000

