server:
  port: 9441

management:
  metrics:
    web:
      server:
        auto-time-requests: false # 关闭⾃动检测请求


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 30
      maxWait: 50000


# 指定zipkin持久化介质为mysql
zipkin:
  storage:
    type: mysql

