#Eureka server服务端⼝
server:
  port: 8761

spring:
  application:
    name: cloud-eureka-server # 应⽤名称，会在Eureka中作为服务的id标识（serviceId）

eureka:
  instance:
    hostname: CloudEurekaServerA
  client:
    service-url: # 客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
      defaultZone: http://CloudEurekaServerB:8762/eureka

    register-with-eureka: true # ⾃⼰就是服务不需要注册⾃⼰，如果是集群，则为true
    #⾃⼰就是服务不需要从Eureka Server获取服务信息,默认为true，置为false,如果是集群，则为true
    fetch-registry: true





