server:
  port: 9999
spring:
  application:
    name: cloud-oauth2-server
eureka:
  client:
    service-url:
      defaultZone:
        http://cloudeurekaservera:8761/eureka/,http://cloudeurekaserverb:8762/eureka/
  instance:
    #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
